# Generated by Django 3.1.3 on 2020-11-17 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('espacio_m2', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('autorizada', models.BooleanField(default=False)),
                ('ultima_rev', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionBrigada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('BR', 'Brigadista'), ('JD', 'Jefe de departamento'), ('RA', 'Responsable'), ('IN', 'Investigador'), ('AL', 'Alumno'), ('EM', 'Empleado'), ('QU', 'Químico')], default='IN', max_length=2)),
                ('fsi_02', models.BooleanField()),
                ('fsi_04', models.BooleanField()),
                ('capacitacion', models.BooleanField()),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.areatrabajo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsabilidadArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.areatrabajo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuimicoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaCovidPositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(null=True)),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('quimico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Control_Servicios_UNISON.quimicoactivo')),
            ],
        ),
        migrations.CreateModel(
            name='JefaturaDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionSanitaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('riesgo', models.IntegerField()),
                ('area_revisada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.areatrabajo')),
                ('brigadista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.asignacionbrigada')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.division'),
        ),
        migrations.AddField(
            model_name='asignacionbrigada',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.division'),
        ),
        migrations.AddField(
            model_name='asignacionbrigada',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areatrabajo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.departamento'),
        ),
    ]
