# Generated by Django 3.1.3 on 2020-11-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Servicios_UNISON', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='rol',
            field=models.CharField(choices=[('BR', 'Brigadista'), ('JD', 'Jefe de departamento'), ('RA', 'Responsable'), ('IN', 'Investigador'), ('AL', 'Alumno'), ('EM', 'Empleado'), ('QU', 'Químico'), ('NA', 'No elegido')], default='IN', max_length=2),
        ),
    ]
