# Generated by Django 3.1.3 on 2020-12-03 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control_Servicios_UNISON', '0006_solicitudapertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatrabajo',
            name='disponibles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='areatrabajo',
            name='usuarios',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SolicitudTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_solici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Servicios_UNISON.areatrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
